# Generated by Django 4.2.5 on 2023-10-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('offer_description', models.TextField()),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('offer_picture', models.ImageField(default='img.jpg', upload_to='image', verbose_name='Изображение')),
                ('cart', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['offer_name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, 'Very Positive'), (4, 'Positive'), (3, 'Neutral'), (2, 'Negative'), (1, 'Very Negative')], null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epood.offer')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
