# Generated by Django 4.2.5 on 2023-10-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='cart',
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Very Positive'), (4, 'Positive'), (3, 'Neutral'), (2, 'Negative'), (1, 'Very Negative')]),
        ),
    ]
